#!/usr/bin/env bash
# gen-en-us.sh — Generate en_US .po entries for all i18n.G() msgids missing from en_US.po
#
# en_US is the sentinel: every msgid in the Go source must have a corresponding
# entry here. This script finds all missing msgids and appends them to en_US.po
# with msgid == msgstr (en_US doesn't translate, it just registers).
#
# Usage:
#   bash gen-en-us.sh
#
# The script modifies internal/i18n/locales/en_US/slingshot.po in-place.
# Run it after adding new i18n.G() calls in Go source code.

set -euo pipefail

REPO="$(cd "$(dirname "$0")/../../../.." && pwd)"
PO_FILE="$REPO/internal/i18n/locales/en_US/slingshot.po"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

TMPDIR=$(mktemp -d)
MISSING_FILE="$TMPDIR/missing.jsonlines"
cleanup() { rm -rf "$TMPDIR"; }
trap cleanup EXIT

cd "$REPO"

# Get missing en_US msgids as JSON lines
python3 "$SCRIPT_DIR/find-missing.py" --po "$PO_FILE" 2>"$TMPDIR/stats.txt" > "$MISSING_FILE"
cat "$TMPDIR/stats.txt" >&2

COUNT=$(wc -l < "$MISSING_FILE")
if [ "$COUNT" -eq 0 ]; then
    echo "✓ No missing en_US entries found."
    exit 0
fi

echo "Appending $COUNT entries to en_US.po..."

# Ensure file ends with newline
if [ "$(tail -c 1 "$PO_FILE" | wc -l)" -eq 0 ]; then
    echo >> "$PO_FILE"
fi

# Add header comment
echo "" >> "$PO_FILE"
echo "# Auto-generated by gen-en-us.sh ($(date +%Y-%m-%d))" >> "$PO_FILE"

# Use Python to process JSON lines and generate .po entries
export MISSING_FILE
python3 << 'PYEOF' >> "$PO_FILE"
import json, sys, os

def escape_po(s):
    s = s.replace('\\', '\\\\')
    s = s.replace('"', '\\"')
    s = s.replace('\n', '\\n')
    return s

def format_entry(msgid):
    """Format a .po entry with msgid == msgstr."""
    has_newline = '\n' in msgid
    if has_newline:
        parts = msgid.split('\n')
        # Remove trailing empty element from split if string ends with \n
        if msgid.endswith('\n') and parts and parts[-1] == '':
            parts = parts[:-1]
        out = ['msgid ""']
        for i, part in enumerate(parts):
            escaped = escape_po(part)
            if i < len(parts) - 1 or msgid.endswith('\n'):
                out.append('"' + escaped + '\\n"')
            else:
                out.append('"' + escaped + '"')
        out.append('msgstr ""')
        for i, part in enumerate(parts):
            escaped = escape_po(part)
            if i < len(parts) - 1 or msgid.endswith('\n'):
                out.append('"' + escaped + '\\n"')
            else:
                out.append('"' + escaped + '"')
        return '\n'.join(out)
    else:
        return 'msgid "' + escape_po(msgid) + '"\nmsgstr "' + escape_po(msgid) + '"'
missing_file = os.environ['MISSING_FILE']
with open(missing_file) as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        try:
            msgid = json.loads(line)
        except json.JSONDecodeError as e:
            print(f"Warning: skipping invalid JSON: {e}", file=sys.stderr)
            continue
        print("")
        print(format_entry(msgid))
PYEOF

echo "✓ Appended $COUNT entries to $PO_FILE"
echo "   Run 'LANG=en_US.UTF-8 go run ./cmd/slingshot/ --help' to verify."
