package main

import (
	"errors"
	"fmt"
	"html"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/fatih/color"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"

	cli "github.com/nanjj/slingshot/internal/cmd"
	"github.com/nanjj/slingshot/internal/config"
	"github.com/nanjj/slingshot/internal/draft"
	"github.com/nanjj/slingshot/internal/getaccesstoken"
	"github.com/nanjj/slingshot/internal/i18n"
	"github.com/nanjj/slingshot/internal/mdtowx"
	"github.com/nanjj/slingshot/internal/uploadcache"
	"github.com/nanjj/slingshot/internal/uploadimage"
	u "github.com/nanjj/slingshot/internal/usage"
)

// draft 子命令语法定义
// 注意: cobra 已处理子命令名 (list/add/update/remove/show/convert),
// 这里只定义子命令后的参数。所有用法使用顶层 atom 序列。

var draftListUsage = u.Usage{}

var draftAddUsage = u.Usage{
	u.File,
}

var draftUpdateUsage = u.Usage{
	u.ID,
	u.File,
}

var draftRemoveUsage = u.Usage{
	u.ID,
}

var draftShowUsage = u.Usage{
	u.ID,
}

// cmdDraft 是 draft 的父命令。
type cmdDraft struct {
	global *cmdGlobal
}

func (c *cmdDraft) command() *cobra.Command {
	cmd := &cobra.Command{}
	cmd.Use = "draft"
	cmd.Short = i18n.G("Manage WeChat drafts")
	cmd.Long = cli.FormatSection(
		color.CyanString("Description:"),
		i18n.G(`Manage WeChat public account drafts.

Subcommands:
  list              List all drafts
  add    <file>     Create a new draft from HTML file
  update <id> <file> Update an existing draft
  remove <id>       Remove a draft
  show   <id>       Show a draft's details
  convert <file>    Convert Markdown to WeChat HTML format
`),
	)
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	}

	// 注册子命令
	cmd.AddCommand(
		c.cmdList().command(),
		c.cmdAdd().command(),
		c.cmdUpdate().command(),
		c.cmdRemove().command(),
		c.cmdShow().command(),
		c.cmdConvert().command(),
	)

	return cmd
}

func (c *cmdDraft) cmdList() *cmdDraftSub {
	return &cmdDraftSub{
		global: c.global,
		name:   "list",
		usage:  draftListUsage,
		short:  i18n.G("List all drafts"),
		long:   i18n.G(`List all WeChat public account drafts with their IDs and titles.`),
		action: c.doList,
	}
}

func (c *cmdDraft) cmdAdd() *cmdDraftAdd {
	return &cmdDraftAdd{
		global: c.global,
	}
}

func (c *cmdDraft) cmdUpdate() *cmdDraftUpdate {
	return &cmdDraftUpdate{
		global: c.global,
	}
}

func (c *cmdDraft) cmdRemove() *cmdDraftSub {
	return &cmdDraftSub{
		global: c.global,
		name:   "remove",
		usage:  draftRemoveUsage,
		short:  i18n.G("Remove a draft"),
		long:   i18n.G(`Remove (delete) a WeChat draft by ID.`),
		action: c.doRemove,
	}
}

func (c *cmdDraft) cmdShow() *cmdDraftSub {
	return &cmdDraftSub{
		global: c.global,
		name:   "show",
		usage:  draftShowUsage,
		short:  i18n.G("Show a draft's details"),
		long:   i18n.G(`Show detailed information about a WeChat draft by ID.`),
		action: c.doShow,
	}
}

func (c *cmdDraft) cmdConvert() *cmdDraftConvert {
	return &cmdDraftConvert{
		global: c.global,
	}
}

// --- cmdDraftAdd ---

// cmdDraftAdd implements "slingshot draft add <file>".
type cmdDraftAdd struct {
	global *cmdGlobal
	title  string
	thumb  string
}

func (c *cmdDraftAdd) command() *cobra.Command {
	cmd := &cobra.Command{}
	cmd.Use = "add " + u.File.Render()
	cmd.Short = i18n.G("Create a new draft from HTML file")
	cmd.Long = cli.FormatSection(
		color.CyanString("Description:"),
		i18n.G(`Create a new WeChat draft from an HTML file (generated by draft convert).

The title is extracted from the <title> tag in the HTML, falling back
to the filename without extension. Use --title to override.

The cover media_id is required by WeChat. Use --thumb to specify, or
include <meta name="thumb_media_id" content="..."> in the HTML.`),
	)
	cmd.Flags().StringVarP(&c.title, "title", "t", "",
		i18n.G("Article title (overrides auto-detection from HTML)"))
	cmd.Flags().StringVarP(&c.thumb, "thumb", "", "",
		i18n.G("Cover image media_id (required; local image file paths are auto-uploaded to WeChat material)"))
	cmd.RunE = c.run
	cmd.Args = cobra.ArbitraryArgs
	return cmd
}

func (c *cmdDraftAdd) run(cmd *cobra.Command, args []string) error {
	parsed, err := c.global.Parse(draftAddUsage, cmd, args)
	if err != nil {
		return err
	}
	if len(parsed) < 1 || parsed[0].Skipped {
		return errors.New(i18n.G("expected a file argument"))
	}
	file := parsed[0].String

	// Read HTML file
	htmlContent, err := os.ReadFile(file)
	if err != nil {
		return fmt.Errorf("reading %q: %w", file, err)
	}
	htmlStr := string(htmlContent)

	// Determine title
	title := c.title
	if title == "" {
		title = extractTitle(htmlStr, file)
	}

	// Validate title
	if err := mdtowx.ValidateTitle(title); err != nil {
		return fmt.Errorf("invalid title: %w", err)
	}

	// Extract and sanitize author
	author := mdtowx.SanitizeAuthor(extractAuthor(htmlStr))

	// Determine cover media_id
	thumbMediaID := c.thumb
	if thumbMediaID == "" {
		thumbMediaID = extractThumbMediaID(htmlStr)
	}
	if thumbMediaID == "" {
		return errors.New(i18n.G("cover media_id is required: use --thumb flag or add <meta name=\"thumb_media_id\" content=\"...\"> to HTML"))
	}

	// Extract digest from HTML meta or sidecar YAML
	digest := extractDigest(htmlStr, file)

	// Load config and get token
	cfg, _, err := config.Load()
	if err != nil {
		return fmt.Errorf("loading config: %w", err)
	}
	token, err := getaccesstoken.GetToken(cfg)
	if err != nil {
		return fmt.Errorf("getting access token: %w", err)
	}

	// Auto-upload thumbnail if the value looks like a local image file path
	if looksLikeImageFile(thumbMediaID) {
		baseDir := filepath.Dir(file)
		thumbPath := thumbMediaID
		if !filepath.IsAbs(thumbPath) {
			thumbPath = filepath.Join(baseDir, thumbPath)
		}
		thumbPath = filepath.Clean(thumbPath)

		if _, err := os.Stat(thumbPath); err == nil {
			// File exists — upload as permanent material
			cache := uploadcache.Load(baseDir)
			key, err := uploadcache.Key(thumbPath)
			if err != nil {
				fmt.Fprintf(cmd.ErrOrStderr(), i18n.G("Warning: checksum failed for thumbnail %s: %v\n"), thumbPath, err)
			} else {
				// Check cache first
				if cachedMediaID, ok := cache.GetMediaID(key); ok && cachedMediaID != "" {
					thumbMediaID = cachedMediaID
					fmt.Fprintf(cmd.OutOrStdout(), i18n.G("Using cached thumbnail %s -> %s\n"),
						filepath.Base(thumbPath), thumbMediaID)
				} else {
					fmt.Fprintf(cmd.OutOrStdout(), i18n.G("Uploading thumbnail %s...\n"), thumbPath)
					mediaID, err := uploadimage.UploadThumb(token, thumbPath)
					if err != nil {
						fmt.Fprintf(cmd.ErrOrStderr(), i18n.G("Warning: thumbnail upload failed for %s: %v\n"), thumbPath, err)
					} else {
						fmt.Fprintf(cmd.OutOrStdout(), i18n.G("Uploaded thumbnail -> media_id: %s\n"), mediaID)
						thumbMediaID = mediaID
						cache.SetMediaID(key, filepath.Base(thumbPath), mediaID)
					}
				}
				// Save cache after thumbnail upload
				if err := cache.Save(); err != nil {
					fmt.Fprintf(cmd.ErrOrStderr(), i18n.G("Warning: failed to save image cache: %v\n"), err)
				}
			}
		} else {
			fmt.Fprintf(cmd.ErrOrStderr(), i18n.G("Warning: thumbnail file %q not found, passing value as-is "+
				"(make sure it's a valid media_id)\n"), thumbPath)
		}
	}

	// Create draft
	resp, err := draft.Add(token, []draft.Article{
		{
			Title:        title,
			Author:       author,
			ThumbMediaID: thumbMediaID,
			Digest:       digest,
			Content:      string(htmlContent),
		},
	})
	if err != nil {
		return fmt.Errorf("creating draft: %w", err)
	}

	fmt.Fprintf(cmd.OutOrStdout(), i18n.G("Draft created: %s\n"), color.GreenString(resp.MediaID))
	return nil
}

// --- cmdDraftUpdate ---

// cmdDraftUpdate implements "slingshot draft update <id> <file>".
type cmdDraftUpdate struct {
	global *cmdGlobal
	title  string
	thumb  string
	index  int
}

func (c *cmdDraftUpdate) command() *cobra.Command {
	cmd := &cobra.Command{}
	cmd.Use = "update " + u.ID.Render() + " " + u.File.Render()
	cmd.Short = i18n.G("Update an existing draft")
	cmd.Long = cli.FormatSection(
		color.CyanString("Description:"),
		i18n.G(`Update an existing WeChat draft by media ID with new HTML content.

The --index flag specifies which article in a multi-article draft to update
(default 0, the first article). Use --thumb to update the cover image.`),
	)
	cmd.Flags().StringVarP(&c.title, "title", "t", "",
		i18n.G("New article title (default: auto-detect from HTML)"))
	cmd.Flags().StringVarP(&c.thumb, "thumb", "", "",
		i18n.G("New cover image media_id (optional; also detected from <meta name=\"thumb_media_id\"> in HTML)"))
	cmd.Flags().IntVarP(&c.index, "index", "i", 0,
		i18n.G("Article index in multi-article draft (0-based)"))
	cmd.RunE = c.run
	cmd.Args = cobra.ArbitraryArgs
	return cmd
}

func (c *cmdDraftUpdate) run(cmd *cobra.Command, args []string) error {
	parsed, err := c.global.Parse(draftUpdateUsage, cmd, args)
	if err != nil {
		return err
	}
	if len(parsed) < 2 || parsed[1].Skipped {
		return errors.New(i18n.G("expected id and file arguments"))
	}
	mediaID := parsed[0].String
	file := parsed[1].String

	// Read HTML file
	htmlContent, err := os.ReadFile(file)
	if err != nil {
		return fmt.Errorf("reading %q: %w", file, err)
	}
	htmlStr := string(htmlContent)

	// Determine title
	title := c.title
	if title == "" {
		title = extractTitle(htmlStr, file)
	}

	// Validate title
	if err := mdtowx.ValidateTitle(title); err != nil {
		return fmt.Errorf("invalid title: %w", err)
	}

	// Extract and sanitize author
	author := mdtowx.SanitizeAuthor(extractAuthor(htmlStr))

	// Determine cover media_id (optional for update)
	thumbMediaID := c.thumb
	if thumbMediaID == "" {
		thumbMediaID = extractThumbMediaID(htmlStr)
	}
	// Load config and get token
	cfg, _, err := config.Load()
	if err != nil {
		return fmt.Errorf("loading config: %w", err)
	}
	token, err := getaccesstoken.GetToken(cfg)
	if err != nil {
		return fmt.Errorf("getting access token: %w", err)
	}

	// Auto-upload thumbnail if the value looks like a local image file path
	if looksLikeImageFile(thumbMediaID) {
		baseDir := filepath.Dir(file)
		thumbPath := thumbMediaID
		if !filepath.IsAbs(thumbPath) {
			thumbPath = filepath.Join(baseDir, thumbPath)
		}
		thumbPath = filepath.Clean(thumbPath)

		if _, err := os.Stat(thumbPath); err == nil {
			// File exists — upload as permanent material
			cache := uploadcache.Load(baseDir)
			key, err := uploadcache.Key(thumbPath)
			if err != nil {
				fmt.Fprintf(cmd.ErrOrStderr(), i18n.G("Warning: checksum failed for thumbnail %s: %v\n"), thumbPath, err)
			} else {
				// Check cache first
				if cachedMediaID, ok := cache.GetMediaID(key); ok && cachedMediaID != "" {
					thumbMediaID = cachedMediaID
					fmt.Fprintf(cmd.OutOrStdout(), i18n.G("Using cached thumbnail %s -> %s\n"),
						filepath.Base(thumbPath), thumbMediaID)
				} else {
					fmt.Fprintf(cmd.OutOrStdout(), i18n.G("Uploading thumbnail %s...\n"), thumbPath)
					mediaID, err := uploadimage.UploadThumb(token, thumbPath)
					if err != nil {
						fmt.Fprintf(cmd.ErrOrStderr(), i18n.G("Warning: thumbnail upload failed for %s: %v\n"), thumbPath, err)
					} else {
						fmt.Fprintf(cmd.OutOrStdout(), i18n.G("Uploaded thumbnail -> media_id: %s\n"), mediaID)
						thumbMediaID = mediaID
						cache.SetMediaID(key, filepath.Base(thumbPath), mediaID)
					}
				}
				// Save cache after thumbnail upload
				if err := cache.Save(); err != nil {
					fmt.Fprintf(cmd.ErrOrStderr(), i18n.G("Warning: failed to save image cache: %v\n"), err)
				}
			}
		} else {
			fmt.Fprintf(cmd.ErrOrStderr(), i18n.G("Warning: thumbnail file %q not found, passing value as-is "+
				"(make sure it's a valid media_id)\n"), thumbPath)
		}
	}

	// Extract digest from sidecar YAML or HTML meta
	digest := extractDigest(htmlStr, file)

	// Build article
	article := draft.Article{
		Title:   title,
		Author:  author,
		Digest:  digest,
		Content: string(htmlContent),
	}
	if thumbMediaID != "" {
		article.ThumbMediaID = thumbMediaID
	}

	// Update draft
	if err := draft.Update(token, mediaID, c.index, article); err != nil {
		return fmt.Errorf("updating draft: %w", err)
	}

	fmt.Fprintf(cmd.OutOrStdout(), i18n.G("Draft updated: %s\n"), color.GreenString(mediaID))
	return nil
}

// --- Actions ---

func (c *cmdDraft) doList(parsed []*u.Parsed, cmd *cobra.Command) error {
	_ = parsed

	cfg, _, err := config.Load()
	if err != nil {
		return fmt.Errorf("loading config: %w", err)
	}
	token, err := getaccesstoken.GetToken(cfg)
	if err != nil {
		return fmt.Errorf("getting access token: %w", err)
	}

	resp, err := draft.List(token, 0, 20)
	if err != nil {
		return fmt.Errorf("listing drafts: %w", err)
	}

	if resp.TotalCount == 0 {
		fmt.Fprintln(cmd.OutOrStdout(), i18n.G("No drafts found."))
		return nil
	}

	// Print table header
	fmt.Fprintf(cmd.OutOrStdout(), "\n%s\n",
		color.CyanString(i18n.G("Drafts (%d total):"), resp.TotalCount))
	fmt.Fprintln(cmd.OutOrStdout(), strings.Repeat("─", 80))

	for i, item := range resp.Items {
		title := i18n.G("(no title)")
		if len(item.Content.Articles) > 0 {
			title = item.Content.Articles[0].Title
		}
		t := time.Unix(item.UpdateTime, 0).Format("2006-01-02 15:04")
		num := fmt.Sprintf("%d.", i+1)
		fmt.Fprintf(cmd.OutOrStdout(), "  %s  %s\n", color.YellowString(num), color.GreenString(title))
		fmt.Fprintf(cmd.OutOrStdout(), "      %s  %s\n",
			color.CyanString(i18n.G("ID:")), item.MediaID)
		fmt.Fprintf(cmd.OutOrStdout(), "      %s  %s\n",
			color.CyanString(i18n.G("Updated:")), t)
		if i < len(resp.Items)-1 {
			fmt.Fprintln(cmd.OutOrStdout())
		}
	}
	fmt.Fprintln(cmd.OutOrStdout(), strings.Repeat("─", 80))
	return nil
}

func (c *cmdDraft) doRemove(parsed []*u.Parsed, cmd *cobra.Command) error {
	if len(parsed) < 1 || parsed[0].Skipped {
		return errors.New(i18n.G("expected an id argument"))
	}
	mediaID := parsed[0].String

	cfg, _, err := config.Load()
	if err != nil {
		return fmt.Errorf("loading config: %w", err)
	}
	token, err := getaccesstoken.GetToken(cfg)
	if err != nil {
		return fmt.Errorf("getting access token: %w", err)
	}

	if err := draft.Remove(token, mediaID); err != nil {
		return fmt.Errorf("removing draft: %w", err)
	}

	fmt.Fprintf(cmd.OutOrStdout(), i18n.G("Draft removed: %s\n"), color.GreenString(mediaID))
	return nil
}

func (c *cmdDraft) doShow(parsed []*u.Parsed, cmd *cobra.Command) error {
	if len(parsed) < 1 || parsed[0].Skipped {
		return errors.New(i18n.G("expected an id argument"))
	}
	mediaID := parsed[0].String

	cfg, _, err := config.Load()
	if err != nil {
		return fmt.Errorf("loading config: %w", err)
	}
	token, err := getaccesstoken.GetToken(cfg)
	if err != nil {
		return fmt.Errorf("getting access token: %w", err)
	}

	resp, err := draft.Show(token, mediaID)
	if err != nil {
		return fmt.Errorf("showing draft: %w", err)
	}

	if len(resp.Articles) == 0 {
		fmt.Fprintln(cmd.OutOrStdout(), i18n.G("Draft has no articles."))
		return nil
	}

	for i, art := range resp.Articles {
		if i > 0 {
			fmt.Fprintln(cmd.OutOrStdout(), strings.Repeat("─", 60))
		}
		fmt.Fprintf(cmd.OutOrStdout(), "%s %d\n", color.CyanString(i18n.G("Article")), i+1)
		fmt.Fprintf(cmd.OutOrStdout(), "  %s  %s\n", color.YellowString(i18n.G("Title:")), art.Title)
		if art.Author != "" {
			fmt.Fprintf(cmd.OutOrStdout(), "  %s  %s\n", color.YellowString(i18n.G("Author:")), art.Author)
		}
		if art.Digest != "" {
			fmt.Fprintf(cmd.OutOrStdout(), "  %s  %s\n", color.YellowString(i18n.G("Digest:")), art.Digest)
		}
		if art.URL != "" {
			fmt.Fprintf(cmd.OutOrStdout(), "  %s  %s\n", color.YellowString(i18n.G("URL:")), art.URL)
		}
		if art.ContentSourceURL != "" {
			fmt.Fprintf(cmd.OutOrStdout(), "  %s  %s\n", color.YellowString(i18n.G("Source URL:")), art.ContentSourceURL)
		}
		fmt.Fprintf(cmd.OutOrStdout(), "  %s  %s\n", color.YellowString(i18n.G("Cover media ID:")), art.ThumbMediaID)
		fmt.Fprintf(cmd.OutOrStdout(), "  %s  %t\n", color.YellowString(i18n.G("Show cover:")), art.ShowCoverPic != 0)
		fmt.Fprintf(cmd.OutOrStdout(), "  %s  %t\n", color.YellowString(i18n.G("Open comments:")), art.NeedOpenComment != 0)
		fmt.Fprintf(cmd.OutOrStdout(), "  %s  %t\n", color.YellowString(i18n.G("Only fans comment:")), art.OnlyFansCanComment != 0)
		if art.Content != "" {
			fmt.Fprintf(cmd.OutOrStdout(), "  %s  %s\n", color.YellowString(i18n.G("Content preview:")),
				truncate(stripTags(art.Content), 120))
		}
	}
	return nil
}

// --- cmdDraftSub ---

// cmdDraftSub 是 draft 的子命令模板（用于 list/remove/show 等无额外标志的子命令）。
type cmdDraftSub struct {
	global *cmdGlobal
	name   string
	usage  u.Usage
	short  string
	long   string
	action func(parsed []*u.Parsed, cmd *cobra.Command) error
}

func (s *cmdDraftSub) command() *cobra.Command {
	cmd := &cobra.Command{}
	cmd.Use = s.name
	cmd.Short = s.short
	cmd.Long = cli.FormatSection(
		color.CyanString("Description:"),
		s.long,
	)
	cmd.RunE = s.run
	cmd.Args = cobra.ArbitraryArgs
	return cmd
}

func (s *cmdDraftSub) run(cmd *cobra.Command, args []string) error {
	parsed, err := s.global.Parse(s.usage, cmd, args)
	if err != nil {
		return err
	}
	return s.action(parsed, cmd)
}

// --- helpers ---

// extractTitle extracts the article title from HTML <title> tag,
// falling back to the filename without extension.
func extractTitle(htmlContent, filePath string) string {
	// Try <title> tag
	lower := strings.ToLower(htmlContent)
	start := strings.Index(lower, "<title>")
	if start >= 0 {
		start += len("<title>")
		end := strings.Index(lower[start:], "</title>")
		if end >= 0 {
			title := htmlContent[start : start+end]
			title = strings.TrimSpace(title)
			title = html.UnescapeString(title)
			if title != "" {
				return title
			}
		}
	}

	// Fallback: filename without extension
	base := filepath.Base(filePath)
	ext := filepath.Ext(base)
	return base[:len(base)-len(ext)]
}

// extractAuthor extracts the author from <meta name="author" content="..."> in HTML.
func extractAuthor(htmlContent string) string {
	lower := strings.ToLower(htmlContent)
	// Match <meta name="author" content="...">
	marker := `<meta name="author" content="`
	start := strings.Index(lower, marker)
	if start < 0 {
		// Try with single quotes
		marker = `<meta name="author" content='`
		start = strings.Index(lower, marker)
		if start < 0 {
			return ""
		}
	}
	start += len(marker)
	end := strings.Index(htmlContent[start:], `"`)
	if end < 0 {
		end = strings.Index(htmlContent[start:], `'`)
	}
	if end < 0 {
		return ""
	}
	author := htmlContent[start : start+end]
	author = strings.TrimSpace(author)
	author = html.UnescapeString(author)
	return author
}

// extractThumbMediaID extracts the cover media_id from
// <meta name="thumb_media_id" content="..."> in HTML.
func extractThumbMediaID(htmlContent string) string {
	lower := strings.ToLower(htmlContent)
	marker := `<meta name="thumb_media_id" content="`
	start := strings.Index(lower, marker)
	if start < 0 {
		// Try with single quotes
		marker = `<meta name="thumb_media_id" content='`
		start = strings.Index(lower, marker)
		if start < 0 {
			return ""
		}
	}
	start += len(marker)
	end := strings.Index(htmlContent[start:], `"`)
	if end < 0 {
		end = strings.Index(htmlContent[start:], `'`)
	}
	if end < 0 {
		return ""
	}
	thumb := htmlContent[start : start+end]
	return strings.TrimSpace(thumb)
}

// stripTags removes HTML tags for preview text.
func stripTags(s string) string {
	var out strings.Builder
	inTag := false
	for _, r := range s {
		if r == '<' {
			inTag = true
			continue
		}
		if r == '>' {
			inTag = false
			continue
		}
		if !inTag {
			out.WriteRune(r)
		}
	}
	return out.String()
}

// truncate truncates a string to maxLen, adding "..." if truncated.
func truncate(s string, maxLen int) string {
	runes := []rune(s)
	if len(runes) <= maxLen {
		return s
	}
	return string(runes[:maxLen]) + "..."
}

// --- Sidecar YAML helpers ---

// sidecarMeta defines the YAML fields that can be stored alongside an HTML file.
type sidecarMeta struct {
	Title        string `yaml:"title"`
	Author       string `yaml:"author"`
	ThumbMediaID string `yaml:"thumb_media_id"`
	Digest       string `yaml:"digest"`
}

// readSidecarYAML attempts to read a sidecar YAML file for the given
// file path. It looks for <filename>.yaml first, then <filename>.yml.
// Returns the parsed metadata and true on success.
func readSidecarYAML(filePath string) (sidecarMeta, bool) {
	base := filePath[:len(filePath)-len(filepath.Ext(filePath))]
	for _, ext := range []string{".yaml", ".yml"} {
		yamlPath := base + ext
		data, err := os.ReadFile(yamlPath)
		if err != nil {
			continue
		}
		var meta sidecarMeta
		if err := yaml.Unmarshal(data, &meta); err != nil {
			continue
		}
		return meta, true
	}
	return sidecarMeta{}, false
}

// extractDigest extracts the digest from sidecar YAML first, falling back
// to <meta name="digest" content="..."> in the HTML content.
func extractDigest(htmlContent, filePath string) string {
	// Prefer sidecar YAML
	if meta, ok := readSidecarYAML(filePath); ok && meta.Digest != "" {
		return meta.Digest
	}
	// Fallback: <meta name="digest" content="..."> in HTML
	lower := strings.ToLower(htmlContent)
	for _, quote := range []string{`"`, `'`} {
		marker := `<meta name="digest" content=` + quote
		start := strings.Index(lower, marker)
		if start < 0 {
			continue
		}
		start += len(marker)
		end := strings.Index(htmlContent[start:], quote)
		if end < 0 {
			continue
		}
		return strings.TrimSpace(htmlContent[start : start+end])
	}
	return ""
}
