package main

import (
	"errors"
	"fmt"
	"html"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/fatih/color"
	"github.com/spf13/cobra"

	cli "github.com/nanjj/slingshot/internal/cmd"
	"github.com/nanjj/slingshot/internal/config"
	"github.com/nanjj/slingshot/internal/draft"
	"github.com/nanjj/slingshot/internal/getaccesstoken"
	"github.com/nanjj/slingshot/internal/i18n"
	"github.com/nanjj/slingshot/internal/mdtowx"
	u "github.com/nanjj/slingshot/internal/usage"
)

// wxdraft 子命令语法定义
// 注意: cobra 已处理子命令名 (list/add/update/remove/show/convert),
// 这里只定义子命令后的参数。所有用法使用顶层 atom 序列。

var wxdraftListUsage = u.Usage{}

var wxdraftAddUsage = u.Usage{
	u.File,
}

var wxdraftUpdateUsage = u.Usage{
	u.ID,
	u.File,
}

var wxdraftRemoveUsage = u.Usage{
	u.ID,
}

var wxdraftShowUsage = u.Usage{
	u.ID,
}

// cmdWxdraft 是 wxdraft 的父命令。
type cmdWxdraft struct {
	global *cmdGlobal
}

func (c *cmdWxdraft) command() *cobra.Command {
	cmd := &cobra.Command{}
	cmd.Use = "wxdraft"
	cmd.Short = i18n.G("Manage WeChat drafts")
	cmd.Long = cli.FormatSection(
		color.CyanString("Description:"),
		i18n.G(`Manage WeChat public account drafts.

Subcommands:
  list              List all drafts
  add    <file>     Create a new draft from HTML file
  update <id> <file> Update an existing draft
  remove <id>       Remove a draft
  show   <id>       Show a draft's details
  convert <file>    Convert Markdown to WeChat HTML format
`),
	)
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	}

	// 注册子命令
	cmd.AddCommand(
		c.cmdList().command(),
		c.cmdAdd().command(),
		c.cmdUpdate().command(),
		c.cmdRemove().command(),
		c.cmdShow().command(),
		c.cmdConvert().command(),
	)

	return cmd
}

func (c *cmdWxdraft) cmdList() *cmdWxdraftSub {
	return &cmdWxdraftSub{
		global: c.global,
		name:   "list",
		usage:  wxdraftListUsage,
		short:  i18n.G("List all drafts"),
		long:   i18n.G(`List all WeChat public account drafts with their IDs and titles.`),
		action: c.doList,
	}
}

func (c *cmdWxdraft) cmdAdd() *cmdWxdraftAdd {
	return &cmdWxdraftAdd{
		global: c.global,
	}
}

func (c *cmdWxdraft) cmdUpdate() *cmdWxdraftUpdate {
	return &cmdWxdraftUpdate{
		global: c.global,
	}
}

func (c *cmdWxdraft) cmdRemove() *cmdWxdraftSub {
	return &cmdWxdraftSub{
		global: c.global,
		name:   "remove",
		usage:  wxdraftRemoveUsage,
		short:  i18n.G("Remove a draft"),
		long:   i18n.G(`Remove (delete) a WeChat draft by ID.`),
		action: c.doRemove,
	}
}

func (c *cmdWxdraft) cmdShow() *cmdWxdraftSub {
	return &cmdWxdraftSub{
		global: c.global,
		name:   "show",
		usage:  wxdraftShowUsage,
		short:  i18n.G("Show a draft's details"),
		long:   i18n.G(`Show detailed information about a WeChat draft by ID.`),
		action: c.doShow,
	}
}

func (c *cmdWxdraft) cmdConvert() *cmdWxdraftConvert {
	return &cmdWxdraftConvert{
		global: c.global,
	}
}

// --- cmdWxdraftAdd ---

// cmdWxdraftAdd implements "slingshot wxdraft add <file>".
type cmdWxdraftAdd struct {
	global *cmdGlobal
	title  string
}

func (c *cmdWxdraftAdd) command() *cobra.Command {
	cmd := &cobra.Command{}
	cmd.Use = "add " + u.File.Render()
	cmd.Short = i18n.G("Create a new draft from HTML file")
	cmd.Long = cli.FormatSection(
		color.CyanString("Description:"),
		i18n.G(`Create a new WeChat draft from an HTML file (generated by wxdraft convert).

The title is extracted from the <title> tag in the HTML, falling back
to the filename without extension. Use --title to override.`),
	)
	cmd.Flags().StringVarP(&c.title, "title", "t", "",
		i18n.G("Article title (overrides auto-detection from HTML)"))
	cmd.RunE = c.run
	cmd.Args = cobra.ArbitraryArgs
	return cmd
}

func (c *cmdWxdraftAdd) run(cmd *cobra.Command, args []string) error {
	parsed, err := c.global.Parse(wxdraftAddUsage, cmd, args)
	if err != nil {
		return err
	}
	if len(parsed) < 1 || parsed[0].Skipped {
		return errors.New(i18n.G("expected a file argument"))
	}
	file := parsed[0].String

	// Read HTML file
	htmlContent, err := os.ReadFile(file)
	if err != nil {
		return fmt.Errorf("reading %q: %w", file, err)
	}
	htmlStr := string(htmlContent)

	// Determine title
	title := c.title
	if title == "" {
		title = extractTitle(htmlStr, file)
	}

	// Validate title
	if err := mdtowx.ValidateTitle(title); err != nil {
		return fmt.Errorf("invalid title: %w", err)
	}

	// Extract and sanitize author
	author := mdtowx.SanitizeAuthor(extractAuthor(htmlStr))
	// Load config and get token
	cfg, _, err := config.Load()
	if err != nil {
		return fmt.Errorf("loading config: %w", err)
	}
	token, err := getaccesstoken.GetToken(cfg)
	if err != nil {
		return fmt.Errorf("getting access token: %w", err)
	}

	// Create draft
	resp, err := draft.Add(token, []draft.Article{
		{
			Title:   title,
			Author:  author,
			Content: string(htmlContent),
		},
	})
	if err != nil {
		return fmt.Errorf("creating draft: %w", err)
	}

	fmt.Fprintf(cmd.OutOrStdout(), i18n.G("Draft created: %s\n"), color.GreenString(resp.MediaID))
	return nil
}

// --- cmdWxdraftUpdate ---

// cmdWxdraftUpdate implements "slingshot wxdraft update <id> <file>".
type cmdWxdraftUpdate struct {
	global *cmdGlobal
	title  string
	index  int
}

func (c *cmdWxdraftUpdate) command() *cobra.Command {
	cmd := &cobra.Command{}
	cmd.Use = "update " + u.ID.Render() + " " + u.File.Render()
	cmd.Short = i18n.G("Update an existing draft")
	cmd.Long = cli.FormatSection(
		color.CyanString("Description:"),
		i18n.G(`Update an existing WeChat draft by media ID with new HTML content.

The --index flag specifies which article in a multi-article draft to update
(default 0, the first article).`),
	)
	cmd.Flags().StringVarP(&c.title, "title", "t", "",
		i18n.G("New article title (default: auto-detect from HTML)"))
	cmd.Flags().IntVarP(&c.index, "index", "i", 0,
		i18n.G("Article index in multi-article draft (0-based)"))
	cmd.RunE = c.run
	cmd.Args = cobra.ArbitraryArgs
	return cmd
}

func (c *cmdWxdraftUpdate) run(cmd *cobra.Command, args []string) error {
	parsed, err := c.global.Parse(wxdraftUpdateUsage, cmd, args)
	if err != nil {
		return err
	}
	if len(parsed) < 2 || parsed[1].Skipped {
		return errors.New(i18n.G("expected id and file arguments"))
	}
	mediaID := parsed[0].String
	file := parsed[1].String

	// Read HTML file
	htmlContent, err := os.ReadFile(file)
	if err != nil {
		return fmt.Errorf("reading %q: %w", file, err)
	}
	htmlStr := string(htmlContent)

	// Determine title
	title := c.title
	if title == "" {
		title = extractTitle(htmlStr, file)
	}

	// Validate title
	if err := mdtowx.ValidateTitle(title); err != nil {
		return fmt.Errorf("invalid title: %w", err)
	}

	// Extract and sanitize author
	author := mdtowx.SanitizeAuthor(extractAuthor(htmlStr))
	// Load config and get token
	cfg, _, err := config.Load()
	if err != nil {
		return fmt.Errorf("loading config: %w", err)
	}
	token, err := getaccesstoken.GetToken(cfg)
	if err != nil {
		return fmt.Errorf("getting access token: %w", err)
	}

	// Update draft
	if err := draft.Update(token, mediaID, c.index, draft.Article{
		Title:   title,
		Author:  author,
		Content: string(htmlContent),
	}); err != nil {
		return fmt.Errorf("updating draft: %w", err)
	}

	fmt.Fprintf(cmd.OutOrStdout(), i18n.G("Draft updated: %s\n"), color.GreenString(mediaID))
	return nil
}

// --- cmdWxdraftSub (通用无标志子命令) ---

// Actions

func (c *cmdWxdraft) doList(parsed []*u.Parsed, cmd *cobra.Command) error {
	_ = parsed

	cfg, _, err := config.Load()
	if err != nil {
		return fmt.Errorf("loading config: %w", err)
	}
	token, err := getaccesstoken.GetToken(cfg)
	if err != nil {
		return fmt.Errorf("getting access token: %w", err)
	}

	resp, err := draft.List(token, 0, 20)
	if err != nil {
		return fmt.Errorf("listing drafts: %w", err)
	}

	if resp.TotalCount == 0 {
		fmt.Fprintln(cmd.OutOrStdout(), i18n.G("No drafts found."))
		return nil
	}

	// Print table header
	fmt.Fprintf(cmd.OutOrStdout(), "\n%s\n",
		color.CyanString(i18n.G("Drafts (%d total):"), resp.TotalCount))
	fmt.Fprintln(cmd.OutOrStdout(), strings.Repeat("─", 80))

	for i, item := range resp.Items {
		title := i18n.G("(no title)")
		if len(item.Content.Articles) > 0 {
			title = item.Content.Articles[0].Title
		}
		t := time.Unix(item.UpdateTime, 0).Format("2006-01-02 15:04")
		num := fmt.Sprintf("%d.", i+1)
		fmt.Fprintf(cmd.OutOrStdout(), "  %s  %s\n", color.YellowString(num), color.GreenString(title))
		fmt.Fprintf(cmd.OutOrStdout(), "      %s  %s\n",
			color.CyanString(i18n.G("ID:")), item.MediaID)
		fmt.Fprintf(cmd.OutOrStdout(), "      %s  %s\n",
			color.CyanString(i18n.G("Updated:")), t)
		if i < len(resp.Items)-1 {
			fmt.Fprintln(cmd.OutOrStdout())
		}
	}
	fmt.Fprintln(cmd.OutOrStdout(), strings.Repeat("─", 80))
	return nil
}


func (c *cmdWxdraft) doRemove(parsed []*u.Parsed, cmd *cobra.Command) error {
	if len(parsed) < 1 || parsed[0].Skipped {
		return errors.New(i18n.G("expected an id argument"))
	}
	mediaID := parsed[0].String

	cfg, _, err := config.Load()
	if err != nil {
		return fmt.Errorf("loading config: %w", err)
	}
	token, err := getaccesstoken.GetToken(cfg)
	if err != nil {
		return fmt.Errorf("getting access token: %w", err)
	}

	if err := draft.Remove(token, mediaID); err != nil {
		return fmt.Errorf("removing draft: %w", err)
	}

	fmt.Fprintf(cmd.OutOrStdout(), i18n.G("Draft removed: %s\n"), color.GreenString(mediaID))
	return nil
}

func (c *cmdWxdraft) doShow(parsed []*u.Parsed, cmd *cobra.Command) error {
	if len(parsed) < 1 || parsed[0].Skipped {
		return errors.New(i18n.G("expected an id argument"))
	}
	mediaID := parsed[0].String

	cfg, _, err := config.Load()
	if err != nil {
		return fmt.Errorf("loading config: %w", err)
	}
	token, err := getaccesstoken.GetToken(cfg)
	if err != nil {
		return fmt.Errorf("getting access token: %w", err)
	}

	resp, err := draft.Show(token, mediaID)
	if err != nil {
		return fmt.Errorf("showing draft: %w", err)
	}

	if len(resp.Articles) == 0 {
		fmt.Fprintln(cmd.OutOrStdout(), i18n.G("Draft has no articles."))
		return nil
	}

	for i, art := range resp.Articles {
		if i > 0 {
			fmt.Fprintln(cmd.OutOrStdout(), strings.Repeat("─", 60))
		}
		fmt.Fprintf(cmd.OutOrStdout(), "%s %d\n", color.CyanString(i18n.G("Article")), i+1)
		fmt.Fprintf(cmd.OutOrStdout(), "  %s  %s\n", color.YellowString(i18n.G("Title:")), art.Title)
		if art.Author != "" {
			fmt.Fprintf(cmd.OutOrStdout(), "  %s  %s\n", color.YellowString(i18n.G("Author:")), art.Author)
		}
		if art.Digest != "" {
			fmt.Fprintf(cmd.OutOrStdout(), "  %s  %s\n", color.YellowString(i18n.G("Digest:")), art.Digest)
		}
		if art.URL != "" {
			fmt.Fprintf(cmd.OutOrStdout(), "  %s  %s\n", color.YellowString(i18n.G("URL:")), art.URL)
		}
		if art.ContentSourceURL != "" {
			fmt.Fprintf(cmd.OutOrStdout(), "  %s  %s\n", color.YellowString(i18n.G("Source URL:")), art.ContentSourceURL)
		}
		fmt.Fprintf(cmd.OutOrStdout(), "  %s  %s\n", color.YellowString(i18n.G("Cover media ID:")), art.ThumbMediaID)
		fmt.Fprintf(cmd.OutOrStdout(), "  %s  %t\n", color.YellowString(i18n.G("Show cover:")), art.ShowCoverPic != 0)
		fmt.Fprintf(cmd.OutOrStdout(), "  %s  %t\n", color.YellowString(i18n.G("Open comments:")), art.NeedOpenComment != 0)
		fmt.Fprintf(cmd.OutOrStdout(), "  %s  %t\n", color.YellowString(i18n.G("Only fans comment:")), art.OnlyFansCanComment != 0)
		if art.Content != "" {
			fmt.Fprintf(cmd.OutOrStdout(), "  %s  %s\n", color.YellowString(i18n.G("Content preview:")),
				truncate(stripTags(art.Content), 120))
		}
	}
	return nil
}

// --- cmdWxdraftSub ---

// cmdWxdraftSub 是 wxdraft 的子命令模板（用于 list/remove/show 等无额外标志的子命令）。
type cmdWxdraftSub struct {
	global *cmdGlobal
	name   string
	usage  u.Usage
	short  string
	long   string
	action func(parsed []*u.Parsed, cmd *cobra.Command) error
}

func (s *cmdWxdraftSub) command() *cobra.Command {
	cmd := &cobra.Command{}
	cmd.Use = s.name
	cmd.Short = s.short
	cmd.Long = cli.FormatSection(
		color.CyanString("Description:"),
		s.long,
	)
	cmd.RunE = s.run
	cmd.Args = cobra.ArbitraryArgs
	return cmd
}

func (s *cmdWxdraftSub) run(cmd *cobra.Command, args []string) error {
	parsed, err := s.global.Parse(s.usage, cmd, args)
	if err != nil {
		return err
	}
	return s.action(parsed, cmd)
}

// --- helpers ---

// extractTitle extracts the article title from HTML <title> tag,
// falling back to the filename without extension.
func extractTitle(htmlContent, filePath string) string {
	// Try <title> tag
	lower := strings.ToLower(htmlContent)
	start := strings.Index(lower, "<title>")
	if start >= 0 {
		start += len("<title>")
		end := strings.Index(lower[start:], "</title>")
		if end >= 0 {
			title := htmlContent[start : start+end]
			title = strings.TrimSpace(title)
			title = html.UnescapeString(title)
			if title != "" {
				return title
			}
		}
	}

	// Fallback: filename without extension
	base := filepath.Base(filePath)
	ext := filepath.Ext(base)
	return base[:len(base)-len(ext)]
}

// extractAuthor extracts the author from <meta name="author" content="..."> in HTML.
func extractAuthor(htmlContent string) string {
	lower := strings.ToLower(htmlContent)
	// Match <meta name="author" content="...">
	marker := `<meta name="author" content="`
	start := strings.Index(lower, marker)
	if start < 0 {
		// Try with single quotes
		marker = `<meta name="author" content='`
		start = strings.Index(lower, marker)
		if start < 0 {
			return ""
		}
	}
	start += len(marker)
	end := strings.Index(htmlContent[start:], `"`)
	if end < 0 {
		end = strings.Index(htmlContent[start:], `'`)
	}
	if end < 0 {
		return ""
	}
	author := htmlContent[start : start+end]
	author = strings.TrimSpace(author)
	author = html.UnescapeString(author)
	return author
}

// stripTags removes HTML tags for preview text.
func stripTags(s string) string {
	var out strings.Builder
	inTag := false
	for _, r := range s {
		if r == '<' {
			inTag = true
			continue
		}
		if r == '>' {
			inTag = false
			continue
		}
		if !inTag {
			out.WriteRune(r)
		}
	}
	return out.String()
}

// truncate truncates a string to maxLen, adding "..." if truncated.
func truncate(s string, maxLen int) string {
	runes := []rune(s)
	if len(runes) <= maxLen {
		return s
	}
	return string(runes[:maxLen]) + "..."
}
