package main

import (
	"fmt"

	"github.com/spf13/cobra"

	cli "github.com/nanjj/slingshot/internal/cmd"
	"github.com/nanjj/slingshot/internal/i18n"
	u "github.com/nanjj/slingshot/internal/usage"
)

// wxdraft 子命令语法定义
// 注意: cobra 已处理子命令名 (list/add/update/remove/show),
// 这里只定义子命令后的参数。所有用法使用顶层 atom 序列。

var wxdraftListUsage = u.Usage{
	u.RemoteColonOpt,
}

var wxdraftAddUsage = u.Usage{
	u.RemoteColonOpt,
	u.File,
}

var wxdraftUpdateUsage = u.Usage{
	u.RemoteColonOpt,
	u.ID,
	u.File,
}

var wxdraftRemoveUsage = u.Usage{
	u.RemoteColonOpt,
	u.ID,
}

var wxdraftShowUsage = u.Usage{
	u.RemoteColonOpt,
	u.ID,
}

// cmdWxdraft 是 wxdraft 的父命令。
type cmdWxdraft struct {
	global *cmdGlobal
}

func (c *cmdWxdraft) command() *cobra.Command {
	cmd := &cobra.Command{}
	cmd.Use = "wxdraft"
	cmd.Short = i18n.G("Manage WeChat drafts")
	cmd.Long = cli.FormatSection(
		fmt.Sprintf("\033[36mDescription:\033[0m"),
		i18n.G(`Manage WeChat public account drafts.

Subcommands:
  list              List all drafts
  add    <file>     Create a new draft from HTML file
  update <id> <file> Update an existing draft
  remove <id>       Remove a draft
  show   <id>       Show a draft's details
`),
	)
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		return cmd.Help()
	}

	// 注册子命令
	cmd.AddCommand(
		c.cmdList().command(),
		c.cmdAdd().command(),
		c.cmdUpdate().command(),
		c.cmdRemove().command(),
		c.cmdShow().command(),
	)

	return cmd
}

func (c *cmdWxdraft) cmdList() *cmdWxdraftSub {
	return &cmdWxdraftSub{
		global: c.global,
		name:   "list",
		usage:  wxdraftListUsage,
		short:  i18n.G("List all drafts"),
		long:   i18n.G(`List all WeChat public account drafts with their IDs and titles.`),
		action: c.doList,
	}
}

func (c *cmdWxdraft) cmdAdd() *cmdWxdraftSub {
	return &cmdWxdraftSub{
		global: c.global,
		name:   "add",
		usage:  wxdraftAddUsage,
		short:  i18n.G("Create a new draft from HTML file"),
		long:   i18n.G(`Create a new WeChat draft from an HTML file (generated by mdtowx).`),
		action: c.doAdd,
	}
}

func (c *cmdWxdraft) cmdUpdate() *cmdWxdraftSub {
	return &cmdWxdraftSub{
		global: c.global,
		name:   "update",
		usage:  wxdraftUpdateUsage,
		short:  i18n.G("Update an existing draft"),
		long:   i18n.G(`Update an existing WeChat draft by ID with new HTML content.`),
		action: c.doUpdate,
	}
}

func (c *cmdWxdraft) cmdRemove() *cmdWxdraftSub {
	return &cmdWxdraftSub{
		global: c.global,
		name:   "remove",
		usage:  wxdraftRemoveUsage,
		short:  i18n.G("Remove a draft"),
		long:   i18n.G(`Remove (delete) a WeChat draft by ID.`),
		action: c.doRemove,
	}
}

func (c *cmdWxdraft) cmdShow() *cmdWxdraftSub {
	return &cmdWxdraftSub{
		global: c.global,
		name:   "show",
		usage:  wxdraftShowUsage,
		short:  i18n.G("Show a draft's details"),
		long:   i18n.G(`Show detailed information about a WeChat draft by ID.`),
		action: c.doShow,
	}
}

// Actions

func (c *cmdWxdraft) doList(parsed []*u.Parsed) error {
	// parsed[0] = RemoteColonOpt (Skipped if not provided)
	fmt.Println(i18n.G("Listing drafts..."))
	_ = parsed
	return nil
}

func (c *cmdWxdraft) doAdd(parsed []*u.Parsed) error {
	// parsed[0] = RemoteColonOpt
	// parsed[1] = File
	if len(parsed) < 2 || parsed[1].Skipped {
		return fmt.Errorf(i18n.G("expected a file argument"))
	}
	file := parsed[1]
	fmt.Printf(i18n.G("Creating draft from %s...\n"), quote(file.String))
	return nil
}

func (c *cmdWxdraft) doUpdate(parsed []*u.Parsed) error {
	// parsed[0] = RemoteColonOpt
	// parsed[1] = ID
	// parsed[2] = File
	if len(parsed) < 3 || parsed[2].Skipped {
		return fmt.Errorf(i18n.G("expected id and file arguments"))
	}
	id := parsed[1]
	file := parsed[2]
	fmt.Printf(i18n.G("Updating draft %s from %s...\n"), quote(id.String), quote(file.String))
	return nil
}

func (c *cmdWxdraft) doRemove(parsed []*u.Parsed) error {
	// parsed[0] = RemoteColonOpt
	// parsed[1] = ID
	if len(parsed) < 2 || parsed[1].Skipped {
		return fmt.Errorf(i18n.G("expected an id argument"))
	}
	id := parsed[1]
	fmt.Printf(i18n.G("Removing draft %s...\n"), quote(id.String))
	return nil
}

func (c *cmdWxdraft) doShow(parsed []*u.Parsed) error {
	// parsed[0] = RemoteColonOpt
	// parsed[1] = ID
	if len(parsed) < 2 || parsed[1].Skipped {
		return fmt.Errorf(i18n.G("expected an id argument"))
	}
	id := parsed[1]
	fmt.Printf(i18n.G("Showing draft %s...\n"), quote(id.String))
	return nil
}

// cmdWxdraftSub 是 wxdraft 的子命令模板。
type cmdWxdraftSub struct {
	global *cmdGlobal
	name   string
	usage  u.Usage
	short  string
	long   string
	action func(parsed []*u.Parsed) error
}

func (s *cmdWxdraftSub) command() *cobra.Command {
	cmd := &cobra.Command{}
	cmd.Use = s.name
	cmd.Short = s.short
	cmd.Long = cli.FormatSection(
		fmt.Sprintf("\033[36mDescription:\033[0m"),
		s.long,
	)
	cmd.RunE = s.run
	cmd.Args = cobra.ArbitraryArgs
	return cmd
}

func (s *cmdWxdraftSub) run(cmd *cobra.Command, args []string) error {
	parsed, err := s.usage.Parse(args)
	if err != nil {
		return err
	}
	return s.action(parsed)
}
